import { useState } from "react";

const API = "http://127.0.0.1:5000";

function Translator({ username }) {
  const [text,      setText]      = useState("");
  const [direction, setDirection] = useState("en-st");
  const [result,    setResult]    = useState(null);
  const [busy,      setBusy]      = useState(false);
  const [error,     setError]     = useState("");

  async function handleTranslate(e) {
    e.preventDefault();
    if (!text.trim()) return;
    setBusy(true); setError(""); setResult(null);

    try {
      const res = await fetch(`${API}/api/translate`, {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({ text, direction, username }),
      });
      if (!res.ok) throw new Error();
      const data = await res.json();
      setResult(data);
    } catch {
      setError("Could not reach the translation backend. Is Flask running?");
    } finally {
      setBusy(false);
    }
  }

  const modelBadge = result?.model === "verified_corpus"
    ? { label: "✅ Verified Corpus Match", bg: "#dcfce7", color: "#15803d" }
    : { label: "🤖 NLLB-200 Neural Translation", bg: "#dbeafe", color: "#1d4ed8" };

  return (
    <div className="card">
      <h2>Translate Medical Phrase</h2>

      <form onSubmit={handleTranslate}>
        <div className="form-row">
          <div className="form-group" style={{ margin: 0 }}>
            <label>Medical Phrase</label>
            <input
              type="text"
              value={text}
              onChange={e => setText(e.target.value)}
              placeholder="e.g. Take one tablet twice daily."
              required
            />
          </div>

          <div className="form-group" style={{ margin: 0 }}>
            <label>Direction</label>
            <select value={direction} onChange={e => setDirection(e.target.value)}>
              <option value="en-st">English → Sesotho</option>
              <option value="st-en">Sesotho → English</option>
            </select>
          </div>
        </div>

        <button
          type="submit"
          className="btn btn-primary"
          style={{ marginTop: 14 }}
          disabled={busy}
        >
          {busy ? "Translating…" : "Translate"}
        </button>
      </form>

      {error && <p className="error-msg" style={{ marginTop: 12 }}>{error}</p>}

      {result && (
        <div style={{ marginTop: 18 }}>
          <label>Translation Output</label>
          <div className="output-box">{result.translated_text}</div>

          {/* Model source badge */}
          <div style={{
            display: "inline-block",
            marginTop: 10,
            padding: "4px 12px",
            borderRadius: 999,
            fontSize: 12,
            fontWeight: 600,
            background: modelBadge.bg,
            color: modelBadge.color,
          }}>
            {modelBadge.label}
          </div>

          <p style={{ fontSize: 11, color: "#94a3b8", marginTop: 6 }}>
            {result.model === "verified_corpus"
              ? "This translation was retrieved from the human-reviewed medical corpus."
              : "This translation was generated by NLLB-200 (facebook/nllb-200-distilled-600M). Always verify medical translations with a qualified professional."}
          </p>
        </div>
      )}
    </div>
  );
}

export default Translator;